name: Manage Subscribers

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email to subscribe/unsubscribe'
        required: true
      action:
        description: 'Action: subscribe or unsubscribe'
        required: true
        default: 'subscribe'

jobs:
  manage_subscribers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug environment variables
      run: env

    - name: Show current directory
      run: pwd

    - name: List current directory contents
      run: ls -la

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Run subscription management script
      run: |
        python manage_subscribers.py ${{ github.event.inputs.action }} ${{ github.event.inputs.email }}

    - name: Check if GH_PAT is set
      run: echo "GH_PAT is set to [${{ secrets.GH_PAT }}]"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add subscribers.json
        git commit -m "Updated subscriber list for ${{ github.event.inputs.action }} ${{ github.event.inputs.email }}"
        git remote -v
        git log -1
        git push https://$GITHUB_TOKEN@github.com/MichaelCrosson/MichaelCrosson.github.io.git HEAD:main
